name: Woechentlicher Highscore Post

on:
  schedule:
    # Jeden Sonntag um 16:00 Uhr UTC (Das entspricht 18:00 Uhr deutscher Sommerzeit)
    - cron: '0 16 * * 0'
  workflow_dispatch: # Erlaubt es dir, das Skript zum Testen manuell per Knopfdruck zu starten

jobs:
  post-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Code herunterladen
        uses: actions/checkout@v3

      - name: Node.js einrichten
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Highscore Skript ausführen
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: run: node dump.js